### ISSUE TITLE
Working?

### ISSUE THREAD

**Issue by raver99** [letscodewithkalyan/MauiMLKitDocumentScanner#1]
Hello @letscodewithkalyan,

Did you manage to get this working? I also need to integrate the ML Kit Document Scanner into MAUI.

I get build errors wihen using the sample in your repo.

Thanks

**Comment by letscodewithkalyan** [comment]
Hi @raver99,
Take latest code and check in real device. But the issue is when we use packages of Jar under binding libraries 
Will get errors. Otherwise project will work fine

**Comment by raver99** [comment]
@letscodewithkalyan, thanks.
Now it works for me as well.

Sorry, i don't understand, can you further explain what you mean by: " But the issue is when we use packages of Jar under binding libraries".

Thank you

**Comment by letscodewithkalyan** [comment]
@raver99 when we add below jar related nugets in project. It will give build errors. need to check this.
<img width="266" alt="Screenshot 2024-11-28 at 12 32 18 PM" src="https://github.com/user-attachments/assets/7cdfe42c-a48f-4d11-ac35-984146d2c08e">
